### ISSUE TITLE
Can't run search example

### ISSUE THREAD

**Issue by devonbrackbill** [byzheng/leafletplugins#1]
Thanks for this package! I'm having trouble getting the example to run from [here](https://byzheng.github.io/leafletplugins/search.html). When I run:

```
    map <- leaflet(data = quakes[1:20,]) %>%
    addTiles() %>%
    addMarkers(~long, ~lat, popup = ~as.character(mag),
            group = 'marker', label = ~as.character(mag))
```
I get an error that the `label` variable is unused:

```
Error in addMarkers(., ~long, ~lat, popup = ~as.character(mag), group = "marker",  : 
  unused argument (label = ~as.character(mag))
```
Also, if I remove the `label` argument, the "Search by popup" command runs, but the search bar never finds anything, no matter what I type in.

Any ideas what I'm doing wrong?

**Comment by devonbrackbill** [comment]
leaflet version 1.0.1
leafletplugins version 0.0.1

**Comment by byzheng** [comment]
Do you  try my fork of leaflet? 

devtools::install_github('byzheng/leaflet')

**Comment by devonbrackbill** [comment]
Thank you! That was the solution. I had previously installed leaflet through CRAN, so it wasn't using your fork.

**Comment by byzheng** [comment]
I think there are lots of new features don't include into CRAN.
